#!/usr/bin/python

import sys;
import marshal;

if len(sys.argv)!=3:
  sys.stderr.write( 'usage:  %s filename integer\n' % (argv[0],) );
  sys.exit(-1);

fp = open( sys.argv[1], 'w' );
fp.write( 'marshalled/python' );
marshal.dump( int(sys.argv[2]), fp );
fp.close();
